- name: Backup XRd Configurations
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure backup directory exists
      ansible.builtin.file:
        path: "{{ backup_path }}"
        state: directory
        mode: '0755'
    
    - name: get timestamp
      local_action: command date +%Y%m%d-%H-%M-%S

      register: timestamp

    - name: Back up running configuration
      cisco.iosxr.iosxr_config:
        backup: yes
        backup_options:
          filename: "{{ backup_path }}/{{ inventory_hostname }}_config_backup_{{ timestamp.stdout }}.cfg"

    - name: Display backup success message
      ansible.builtin.debug:
        msg: "Backup for {{ inventory_hostname }} completed successfully."
