---
- hosts: all
  gather_facts: false  # Since we're using NAPALM
  connection: local     #  Though we'll connect via SSH
  
  vars:
    napalm_connection_options:  # Common options, override per-task if needed
      transport: cli # Or 'rest' if your XR supports it and you have the correct setup
      # The user/password will ideally come from Ansible Vault for production
      username: cisco 
      password: cisco123
      # Optional: For SSH key-based authentication
      #ssh_keyfile: /path/to/your/key

  tasks:

    - name: Establish NAPALM connection
      napalm_connection:
        hostname: 172.20.2.201 # Or a variable if you prefer
        # Combine connection options. Override defaults here if needed.
        # For example:  port: 2222, timeout: 30
        options: "{{ napalm_connection_options }}" 
      register: napalm_connection # Save the connection object

    - name: Get facts from the device (example)
      napalm_get_facts:
        connection: "{{ napalm_connection.connection }}"
      register: facts

    - debug:
        msg: "Hostname: {{ facts.ansible_facts.net_hostname }}"

    - name: Run a command
      napalm_cli:
        connection: "{{ napalm_connection.connection }}"
        commands:
          - show ip interface brief
      register: cli_output

    - debug:
        msg: "{{ cli_output.ansible_facts.napalm_cli }}"
