---
- name: Run a command on a Cisco IOS-XR router using NAPALM
  hosts: iosxr_routers
  gather_facts: no
  connection: local
  tasks:
    - name: Run "show version" command on the router
      ansible.netcommon.napalm:
        commands:
          - "show version"
      register: command_output

    - name: Display command output
      debug:
        msg: "{{ command_output }}"